// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDhjvZx5zcxMQs5kCTVRRBCjzRN_CBlU',
    appId: '1:328044287708:web:cebec26dadfa31909ec619',
    messagingSenderId: '328044287708',
    projectId: 'dotcode-e21c4',
    authDomain: 'dotcode-e21c4.firebaseapp.com',
    storageBucket: 'dotcode-e21c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6iN57Lnd4hAjNWM1LP_v2DZNwG3sz8Y4',
    appId: '1:328044287708:android:5a3762e8d599711a9ec619',
    messagingSenderId: '328044287708',
    projectId: 'dotcode-e21c4',
    storageBucket: 'dotcode-e21c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wUNcvvib3WCDXgXJpBbaiUDFhvRy6O8',
    appId: '1:328044287708:ios:a489954b8d252e439ec619',
    messagingSenderId: '328044287708',
    projectId: 'dotcode-e21c4',
    storageBucket: 'dotcode-e21c4.appspot.com',
    iosClientId: '328044287708-d3q7mdcjf87bufv0vgjd7spmq7olpnel.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
